### ISSUE TITLE
limit number of hotspots in include these

### ISSUE THREAD

**Issue by mylesstokowski** [abigailstone/optimal-big-day#1]
![image](https://user-images.githubusercontent.com/35432444/121818604-2da56580-cc56-11eb-9bdd-e1a8d5e8a73b.png)

user should not be able to select more hotspots to include (in the last field) than the number of hotspots to visit (the third field)

**Comment by mylesstokowski** [comment]
handled with most recent commit

**Comment by mylesstokowski** [comment]
<img width="1440" alt="Screen Shot 2021-08-07 at 2 11 52 PM" src="https://user-images.githubusercontent.com/35432444/128744621-8741c543-f97e-4ec6-aab7-0c90ee2e3e77.png">
appears this is not actually handled!

**Comment by abigailstone** [comment]
The number of hotspots in includeThese is limited, but when the number of hotspots specified is equal to the number of hotspots selected in includeThese, the result returns n+2 hotspots. I'm pretty sure the limiting part is fixed so I'll close this and open a separate issue.
