### ISSUE TITLE
predicted total species bug

### ISSUE THREAD

**Issue by mylesstokowski** [abigailstone/optimal-big-day#2]
![image](https://user-images.githubusercontent.com/35432444/121818654-837a0d80-cc56-11eb-900c-59cc022bd982.png)

unless I'm missing something, predicted total species should always be greater than the predicted number of species for each individual hotspot

in this example, Button Bay has 38 species but the total predicted species is just 32

**Comment by abigailstone** [comment]
This seems to happen when "include these" hotspots have been specified. The predicted total at the bottom is currently an extremely hacky computation - I pulled the ```current_best``` value from the greedy selection and called it the predicted total....this is only mathematically correct if nothing is specified for "include these" and all _k_ hotspots are selected greedily.

Long story short, I'll throw the predicted total calculation into its own function and de-hack-ify it.
