### ISSUE TITLE
When the number of includeThese hotspots == nHotspots, there are 2 additional hotspots included in results

### ISSUE THREAD

**Issue by abigailstone** [abigailstone/optimal-big-day#5]
When the number of hotspots written into the includeThese field is less than the total hotspots specified, we get the expected output:
![n2](https://user-images.githubusercontent.com/43352075/132254860-36bd8699-9ba4-439f-8a2a-59f91401f1d6.png)

When we add another hotspot to the includeThese field such that the number included in includeThese is _equal_ to the number specified in nHotspots, we get two additional hotspot suggestions in the results table:
![n3](https://user-images.githubusercontent.com/43352075/132254935-e58d3604-7303-49b3-b437-19c5bce89a84.png)

This n+2 number of suggestions seems to be consistent (ie independent of the value specified for nHotspots).

**Comment by abigailstone** [comment]
This is happening inside the hotspot selection code (see fct_find_hotspots.R). When we select hotspots, we pass the includeThese hotspots as a character vector, and then iterate through the remaining number that we need to select with the greedy selection. That for-loop iterates like so: `for(i in 1:k-length(H)))`, where `k`is the total number of hotspots to select and `H` is our character vector of pre-selected hotspots. 

Currently we're allowing the user to include up to _k_ hotspots in the include field. When the number to include is less than _k_, the for-loop works as expected:

- if the user wants to visit 3 hotspots and doesn't specify any, `select_hotspots` iterates from 1:3 and produces 3 results
- if the user wants to visit 3 hotspots and specifies two of them, we get the two specified results and then the for-loop iterates 1:1 and outputs a single third result.

However, if we specify exactly _k_ hotspots, we'd expect to just see the predicted totals for our selected locations without any additional suggested locations. Since our `length(H)` is now equal to `k`, the for-loop tries to iterate 1:0, which in R is two iterations...so we we have these two additional results that exceed the _k_ that we asked for.

We have a couple options for fixing this:
- limit the user to _k_-1 hotspots to specify (this is a little hack-y and we'd lose the ability to just do a probability estimate on a pre-specified group of hotspots without any greedy selection)
- change the way we handle the for-loop so we don't get wacky 1:0 iteration
- throw in a line that skips the greedy selection if `k` is equal to `length(H)` 
- something else entirely??

**Comment by mylesstokowski** [comment]
Nice find! 

Could you use `seq_len` rather than `1: x`

Example:
> for (i in seq_len(0)) print(i)
> for (i in 1:0) print(i)
[1] 1
[1] 0

**Comment by abigailstone** [comment]
Brilliant! fixed!
